//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Draghts.DraughtsServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Piece", Namespace="http://schemas.datacontract.org/2004/07/Draught")]
    [System.SerializableAttribute()]
    public partial class Piece : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XCoordinateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YCoordinateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XCoordinate {
            get {
                return this.XCoordinateField;
            }
            set {
                if ((this.XCoordinateField.Equals(value) != true)) {
                    this.XCoordinateField = value;
                    this.RaisePropertyChanged("XCoordinate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YCoordinate {
            get {
                return this.YCoordinateField;
            }
            set {
                if ((this.YCoordinateField.Equals(value) != true)) {
                    this.YCoordinateField = value;
                    this.RaisePropertyChanged("YCoordinate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoardSquare", Namespace="http://schemas.datacontract.org/2004/07/Draught")]
    [System.SerializableAttribute()]
    public partial class BoardSquare : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XCoordinateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YCoordinateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XCoordinate {
            get {
                return this.XCoordinateField;
            }
            set {
                if ((this.XCoordinateField.Equals(value) != true)) {
                    this.XCoordinateField = value;
                    this.RaisePropertyChanged("XCoordinate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YCoordinate {
            get {
                return this.YCoordinateField;
            }
            set {
                if ((this.YCoordinateField.Equals(value) != true)) {
                    this.YCoordinateField = value;
                    this.RaisePropertyChanged("YCoordinate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Draught", ConfigurationName="DraughtsServiceReference.IPortal")]
    public interface IPortal {
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IPortal/signUp", ReplyAction="Draught/IPortal/signUpResponse")]
        bool signUp(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IPortal/signUp", ReplyAction="Draught/IPortal/signUpResponse")]
        System.Threading.Tasks.Task<bool> signUpAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IPortal/logIn", ReplyAction="Draught/IPortal/logInResponse")]
        bool logIn(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IPortal/logIn", ReplyAction="Draught/IPortal/logInResponse")]
        System.Threading.Tasks.Task<bool> logInAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IPortal/Invite", ReplyAction="Draught/IPortal/InviteResponse")]
        bool Invite(string recipient);
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IPortal/Invite", ReplyAction="Draught/IPortal/InviteResponse")]
        System.Threading.Tasks.Task<bool> InviteAsync(string recipient);
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IPortal/logOut", ReplyAction="Draught/IPortal/logOutResponse")]
        void logOut();
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IPortal/logOut", ReplyAction="Draught/IPortal/logOutResponse")]
        System.Threading.Tasks.Task logOutAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPortalChannel : Draghts.DraughtsServiceReference.IPortal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PortalClient : System.ServiceModel.ClientBase<Draghts.DraughtsServiceReference.IPortal>, Draghts.DraughtsServiceReference.IPortal {
        
        public PortalClient() {
        }
        
        public PortalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PortalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool signUp(string userName, string password) {
            return base.Channel.signUp(userName, password);
        }
        
        public System.Threading.Tasks.Task<bool> signUpAsync(string userName, string password) {
            return base.Channel.signUpAsync(userName, password);
        }
        
        public bool logIn(string userName, string password) {
            return base.Channel.logIn(userName, password);
        }
        
        public System.Threading.Tasks.Task<bool> logInAsync(string userName, string password) {
            return base.Channel.logInAsync(userName, password);
        }
        
        public bool Invite(string recipient) {
            return base.Channel.Invite(recipient);
        }
        
        public System.Threading.Tasks.Task<bool> InviteAsync(string recipient) {
            return base.Channel.InviteAsync(recipient);
        }
        
        public void logOut() {
            base.Channel.logOut();
        }
        
        public System.Threading.Tasks.Task logOutAsync() {
            return base.Channel.logOutAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Draught", ConfigurationName="DraughtsServiceReference.IGamePlay")]
    public interface IGamePlay {
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IGamePlay/move", ReplyAction="Draught/IGamePlay/moveResponse")]
        void move(int newX, int newY);
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IGamePlay/move", ReplyAction="Draught/IGamePlay/moveResponse")]
        System.Threading.Tasks.Task moveAsync(int newX, int newY);
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IGamePlay/sendMessage", ReplyAction="Draught/IGamePlay/sendMessageResponse")]
        bool sendMessage(string recipient, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IGamePlay/sendMessage", ReplyAction="Draught/IGamePlay/sendMessageResponse")]
        System.Threading.Tasks.Task<bool> sendMessageAsync(string recipient, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IGamePlay/makeMove", ReplyAction="Draught/IGamePlay/makeMoveResponse")]
        bool makeMove(Draghts.DraughtsServiceReference.Piece piece, Draghts.DraughtsServiceReference.BoardSquare boardSquare);
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IGamePlay/makeMove", ReplyAction="Draught/IGamePlay/makeMoveResponse")]
        System.Threading.Tasks.Task<bool> makeMoveAsync(Draghts.DraughtsServiceReference.Piece piece, Draghts.DraughtsServiceReference.BoardSquare boardSquare);
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IGamePlay/Subscribe", ReplyAction="Draught/IGamePlay/SubscribeResponse")]
        void Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IGamePlay/Subscribe", ReplyAction="Draught/IGamePlay/SubscribeResponse")]
        System.Threading.Tasks.Task SubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IGamePlay/quitGame", ReplyAction="Draught/IGamePlay/quitGameResponse")]
        void quitGame();
        
        [System.ServiceModel.OperationContractAttribute(Action="Draught/IGamePlay/quitGame", ReplyAction="Draught/IGamePlay/quitGameResponse")]
        System.Threading.Tasks.Task quitGameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGamePlayChannel : Draghts.DraughtsServiceReference.IGamePlay, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GamePlayClient : System.ServiceModel.ClientBase<Draghts.DraughtsServiceReference.IGamePlay>, Draghts.DraughtsServiceReference.IGamePlay {
        
        public GamePlayClient() {
        }
        
        public GamePlayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GamePlayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GamePlayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GamePlayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void move(int newX, int newY) {
            base.Channel.move(newX, newY);
        }
        
        public System.Threading.Tasks.Task moveAsync(int newX, int newY) {
            return base.Channel.moveAsync(newX, newY);
        }
        
        public bool sendMessage(string recipient, string message) {
            return base.Channel.sendMessage(recipient, message);
        }
        
        public System.Threading.Tasks.Task<bool> sendMessageAsync(string recipient, string message) {
            return base.Channel.sendMessageAsync(recipient, message);
        }
        
        public bool makeMove(Draghts.DraughtsServiceReference.Piece piece, Draghts.DraughtsServiceReference.BoardSquare boardSquare) {
            return base.Channel.makeMove(piece, boardSquare);
        }
        
        public System.Threading.Tasks.Task<bool> makeMoveAsync(Draghts.DraughtsServiceReference.Piece piece, Draghts.DraughtsServiceReference.BoardSquare boardSquare) {
            return base.Channel.makeMoveAsync(piece, boardSquare);
        }
        
        public void Subscribe() {
            base.Channel.Subscribe();
        }
        
        public System.Threading.Tasks.Task SubscribeAsync() {
            return base.Channel.SubscribeAsync();
        }
        
        public void quitGame() {
            base.Channel.quitGame();
        }
        
        public System.Threading.Tasks.Task quitGameAsync() {
            return base.Channel.quitGameAsync();
        }
    }
}
